# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Of blasters, and droids.'
tagline:          '(a work in progress)'
description:      'Lock the doors. And hope they dont have blasters.'
url:              http://noahschmitz.github.io

author:
  name:           'Noah Schmitz'
  url:            https://noahschmitz.info

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon

prose:
  rooturl: '_posts'
  siteurl: 'http://noahschmitz.github.io/'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Title"
          value: ""
