# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Of blasters, etc.'
tagline:          '(a work in progress)'
description:      'A blog, for blogging about my blog. On my blog.'
url:              http://noahschmitz.github.io

author:
  name:           'Noah Schmitz'
  url:            https://noahschmitz.info

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
